=== liutao1024/github-mvn/spring-mvn-admin/spring-mvn-socket/src/main/resources/xml/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.w3school.com.cn" xmlns="http://www.w3school.com.cn" elementFormDefault="qualified">
	<xs:attribute name="lang" type="xs:string" fixed="EN" />
	<!-- 以上部分为实验,下部分是开始定义接口来 -->
	<xs:element name="flowtran" type="flowtranConf" />
	<xs:complexType name="flowtranConf">
		<xs:sequence>
			<xs:element name="description" type="xs:string" minOccurs="0" />
			<xs:element name="interface" type="interfaceData" minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" />
		<xs:attribute name="longname" type="xs:string" />
		<xs:attribute name="package" type="xs:string" />
	</xs:complexType>
	<xs:complexType name="interfaceData">
		<xs:sequence>
			<xs:element name="sys" minOccurs="0">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="interfaceElements">
							<xs:sequence />
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="comm" minOccurs="0">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="interfaceElements">
							<xs:sequence />
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="input" minOccurs="0">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="interfaceElements">
							<xs:sequence />
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="output" minOccurs="0">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="interfaceElements">
							<xs:sequence />
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="interfaceElements" abstract="true">
		<xs:sequence>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="fields" type="interfaceFields" />
				<xs:element name="field" type="interfaceField" />
			</xs:choice>
			<xs:element name="validations" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:element name="validation" type="validation" />
							<xs:element name="expression" type="expressionRule" />
						</xs:choice>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="packMode" type="xs:boolean" />
		<xs:attribute name="class" type="xs:string" />
		<xs:attribute name="package" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="interfaceFields">
		<xs:sequence>
			<xs:element name="depends" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="depend" type="depend" minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="validations" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:element name="validation" type="validation" />
							<xs:element name="expression" type="expressionRule" />
						</xs:choice>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="fields" type="interfaceFields" />
				<xs:element name="field" type="interfaceField" />
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" />
		<xs:attribute name="alias" type="xs:string" />
		<xs:attribute name="scope" type="xs:string" />
		<xs:attribute name="required" type="xs:boolean" />
		<xs:attribute name="multi" type="xs:boolean" />
		<xs:attribute name="longname" type="xs:string" />
		<xs:attribute name="desc" type="xs:string" />
		<xs:attribute name="array" type="xs:boolean" />
		<xs:attribute name="relation" type="xs:string" />
		<xs:attribute name="values" type="xs:string" />
		<xs:attribute name="lazyLoad" type="xs:boolean" />
		<xs:attribute name="property" type="xs:string" />
		<xs:attribute name="ref" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="interfaceField">
		<xs:sequence>
			<xs:element name="depends" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="depend" type="depend" minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="validations" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:element name="validation" type="validation" />
							<xs:element name="expression" type="expressionRule" />
						</xs:choice>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" />
		<xs:attribute name="alias" type="xs:string" />
		<xs:attribute name="type" type="xs:string" />
		<xs:attribute name="required" type="xs:boolean" />
		<xs:attribute name="enums" type="xs:string" />
		<xs:attribute name="fixed" type="xs:string" />
		<xs:attribute name="default" type="xs:string" />
		<xs:attribute name="multi" type="xs:boolean" />
		<xs:attribute name="array" type="xs:boolean" />
		<xs:attribute name="longname" type="xs:string" />
		<xs:attribute name="alias_name" type="xs:string" />
		<xs:attribute name="additionalType" type="xs:string" />
		<xs:attribute name="desc" type="xs:string" />
		<xs:attribute name="lazyLoad" type="xs:boolean" />
		<xs:attribute name="values" type="xs:string" />
		<xs:attribute name="relation" type="xs:string" />
		<xs:attribute name="desplay" type="xs:boolean" />
		<xs:attribute name="ref" type="xs:string" />
		<xs:attribute name="property" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="validation">
		<xs:complexContent>
			<xs:extension base="rule">
				<xs:sequence />
				<xs:attribute name="id" type="xs:string" />
				<xs:attribute name="method" type="xs:string" />
				<xs:attribute name="target" type="xs:string" />
				<xs:attribute name="message" type="xs:string" />
				<xs:attribute name="ajax" type="xs:boolean" />
				<xs:attribute name="errorCode" type="xs:string" />
				<xs:attribute name="depends">
					<xs:simpleType>
						<xs:list itemType="xs:string" />
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="expressionRule">
		<xs:complexContent>
			<xs:extension base="rule">
				<xs:sequence />
				<xs:attribute name="id" type="xs:string" />
				<xs:attribute name="target" type="xs:string" />
				<xs:attribute name="top" type="operateType" />
				<xs:attribute name="tval" type="xs:string" />
				<xs:attribute name="errorCode" type="xs:string" />
				<xs:attribute name="ajax" type="xs:boolean" />
				<xs:attribute name="message" type="xs:string" />
				<xs:attribute name="depends">
					<xs:simpleType>
						<xs:list itemType="xs:string" />
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="depend">
		<xs:complexContent>
			<xs:extension base="rule">
				<xs:sequence />
				<xs:attribute name="message" type="xs:string" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="rule">
		<xs:sequence>
			<xs:choice minOccurs="0">
				<xs:element name="mvel" type="mvel" />
				<xs:element name="javascript" type="javascript" />
				<xs:element name="or" type="or" />
				<xs:element name="and" type="and" />
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="not" type="xs:boolean" />
		<xs:attribute name="when" type="xs:string" />
		<xs:attribute name="op" type="operateType" /><!-- operateType -->
		<xs:attribute name="val" type="xs:string" />
		<xs:attribute name="desc" type="xs:string" />
	</xs:complexType>

	<xs:simpleType name="operateType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="lt" />
			<xs:enumeration value="gt" />
			<xs:enumeration value="eq" />
			<xs:enumeration value="neq" />
			<xs:enumeration value="in" />
			<xs:enumeration value="notIn" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="mvel">
		<xs:restriction base="xs:string" />
	</xs:simpleType>

	<xs:simpleType name="javascript">
		<xs:restriction base="xs:string" />
	</xs:simpleType>

	<xs:complexType name="or">
		<xs:sequence>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="rule" type="rule" />
				<xs:element name="or" type="or" />
				<xs:element name="and" type="and" />
			</xs:choice>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="and">
		<xs:sequence>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="rule" type="rule" />
				<xs:element name="or" type="or" />
				<xs:element name="and" type="and" />
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	
</xs:schema>

=== liutao1024/github-mvn/spring-mvn-admin/spring-mvn-socket/src/main/resources/port/qrcust.xml
<?xml version="1.0" encoding="UTF-8"?>
<flowtran id="qrcust" longname="客户信息查询" package="cn.spring.mvn.core.account.zport" 
	xmlns="http://www.w3school.com.cn" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.w3school.com.cn ../xml/schema.xsd"><!-- 引入自己的scheme 为什么在../scheme/scheme.xsd不行? -->
	<description></description>
	<interface>
		<sys packMode="true" class="cn.spring.mvn.socket.Sys">
			<field id="servtp" type="xs:string" required="false" multi="false" array="false" longname="渠道类型 " ref=""/>
			<field id="servno" type="xs:string" required="false" multi="false" array="false" longname="渠道号 " ref=""/>
			<field id="servdt" type="xs:string" required="false" multi="false" array="false" longname="渠道日期 " ref=""/>
			<field id="servtm" type="xs:string" required="false" multi="false" array="false" longname="渠道时间 " ref=""/>
			<field id="servsq" type="xs:string" required="false" multi="false" array="false" longname="渠道流水 " ref=""/>
			<field id="tranbr" type="xs:string" required="false" multi="false" array="false" longname="交易机构 " ref=""/>
			<field id="tranus" type="xs:string" required="false" multi="false" array="false" longname="交易柜员" ref=""/>
			<field id="trandt" type="xs:string" required="false" multi="false" array="false" longname="交易日期" ref=""/>
			<field id="trantm" type="xs:string" required="false" multi="false" array="false" longname="交易时间" ref=""/>
			<field id="transq" type="xs:string" required="false" multi="false" array="false" longname="交易流水 " ref=""/>
			<field id="status" type="xs:string" required="false" multi="false" array="false" longname="交易状态" ref=""/>
			<field id="mesage" type="xs:string" required="false" multi="false" array="false" longname="交易信息 " ref=""/>
		</sys>
		<comm packMode="true" class="cn.spring.mvn.socket.Comm">
			<field id="corpno" type="xs:string" required="false" multi="false" array="false" longname="法人代码 " ref=""/>
			<field id="prcscd" type="xs:string" required="false" multi="false" array="false" longname="交易处理码 " ref=""/>
		</comm>
		<input packMode="true" class="cn.spring.mvn.core.account.zport.QrcustInput" package="cn.spring.mvn.core.account.zport">
			<field id="custno" type="xs:string" required="false" multi="false" array="false" longname="客户号 " ref=""/>
			<field id="custna" type="xs:string" required="false" multi="false" array="false" longname="客户名称 " ref=""/>
		</input>																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																						
		<output packMode="true" class="cn.spring.mvn.core.account.zport.QrcustOutput" package="cn.spring.mvn.core.account.zport">
			<field id="count" type="xs:int" required="false" multi="false" array="false" longname="记录数 " ref=""/>
			<fields id="infos" scope="" required="false" multi="true" longname="信息集合" array="false">
                <field id="custno" type="xs:string" required="false" multi="false" array="false" longname="客户号" ref=""/>
                <field id="custna" type="xs:string" required="false" multi="false" array="false" longname="客户名" ref=""/>
                <field id="custsx" type="xs:string" required="false" multi="false" array="false" longname="客户性别" ref=""/>
                <field id="idtftp" type="xs:string" required="false" multi="false" array="false" longname="证件类型" ref=""/>
                <field id="idtfno" type="xs:string" required="false" multi="false" array="false" longname="证件号码" ref=""/>
            </fields>
		</output>
	</interface>
</flowtran>

=== liutao1024/github-mvn/spring-mvn-admin/spring-mvn-socket/src/main/resources/interface/qrcust1.xml
<?xml version="1.0" encoding="UTF-8"?>
<flowtran id="qrcust" longname="客户信息查询" package="cn.spring.mvn.core.account.zRDI" xmlns="http://www.w3school.com.cn" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.w3school.com.cn ../xml/schema.xsd"><!-- 引入自己的scheme -->
	<description></description>
	<interface>
		<sys>
			<field id="custno" type="xs:string" required="false" multi="false" array="false" longname="客户号 " ref="ClDict.CL.custno"/>
		</sys>
		<comm>
			<field id="custno" type="xs:string" required="false" multi="false" array="false" longname="客户号 " ref="ClDict.CL.custno"/>
		</comm>
		<input>
			<field id="custno" type="xs:string" required="false" multi="false" array="false" longname="客户号 " ref="ClDict.CL.custno"/>
		</input>
		<output>
			<field id="custno" type="xs:string" required="false" multi="false" array="false" longname="客户号 " ref="ClDict.CL.custno"/>
			<fields id="addlst" scope="IoClAdd.AddList" required="false" multi="true" longname="级别集合" array="false">
                <field id="busino" type="BaseType.U_CHAR20" required="false" multi="false" array="false" longname="产品号/账号/卡号/上级客户号/交易渠道" ref="ClDict.CL.busino"/>
                <field id="crdlam" type="BaseType.U_ACBLTP" required="false" multi="false" array="false" longname="额度金额" ref="ClDict.CL.crdlam"/>
                <field id="cllevl" type="ClEnumType.E_CLLEVL" required="false" multi="false" array="false" longname="额度级别" ref="ClDict.CL.cllevl"/>
                <field id="status" type="ClEnumType.E_STATUS" required="false" multi="false" array="false" longname="额度状态" ref="ClDict.CL.status"/>
            </fields>
		</output>
	</interface>
</flowtran>
